apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-test-prod
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sdouglas1-tenant/multi-platform-test-prod/multi-platform-test-prod@sha256:7df140e0e18685e40eeca1bed042683f6626f2235fa1ba2fef4bfddce63fa3bb
        name: my-go
        resources: {}
status: {}
